analyzer:
 strong-mode:
   true
   ### Useful to uncomment during development to catch errors.
   # implicit-dynamic: false
   # implicit-casts: false
 exclude:
    # This exclude does not work on Dart 1.24.x
    # See `tool/travis.sh` for this is handled on Travis
    - tools/analyzer_plugin/bin/plugin.dart
 errors:
   unused_element: error
   unused_import: error
   unused_local_variable: error
   dead_code: error

   # Allow importing .template.dart files without an analyzer error.
   uri_has_not_been_generated: ignore

   ### Useful to uncomment during development to remove the noise of the many
   ### deprecated APIs.
   # deprecated_member_use: ignore
linter:
  rules:
    #- always_declare_return_types
    #- always_specify_types
    #- annotate_overrides
    #- avoid_as
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    #- avoid_return_types_on_setters
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    #- close_sinks
    #- comment_references
    #- constant_identifier_names
    - control_flow_in_finally
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    #- implementation_imports
    - iterable_contains_unrelated_type
    - library_names
    - library_prefixes
    - list_remove_unrelated_type
    #- non_constant_identifier_names
    #- one_member_abstracts
    #- only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_final_fields
    - prefer_is_not_empty
    #- public_member_api_docs
    - slash_for_doc_comments
    #- sort_constructors_first
    #- sort_unnamed_constructors_first
    - super_goes_last
    - test_types_in_equals
    - throw_in_finally
    #- type_annotate_public_apis
    - type_init_formals
    #- unawaited_futures
    - unnecessary_brace_in_string_interps
    #- unnecessary_getters_setters
    - unrelated_type_equality_checks
    - valid_regexps
