# Extend the default sub-set of linter/analyzer rules used in google3.
include: ../../../dart/analysis_options/lib/default.yaml

analyzer:
  errors:
    # Permanent exclusions: Unlikely to removed.
    # =====================
    # Allow importing .template.dart files without an [explicit] analyzer error.
    uri_has_not_been_generated: ignore
    # Ignore our own deprecated symbols (too noisy).
    deprecated_member_use_from_same_package: ignore
    # Allow having TODOs in the code (too noisy).
    todo: ignore

    # Security exclusions: We are security reviewed separate from these lints.
    # =====================
    avoid_bypassing_html_security: ignore
    avoid_dynamic_execution: ignore
    avoid_unsafe_apis: ignore
    unsafe_html: ignore

    # Temporary exclusions: Can be removed in the future.
    # =====================
    # Re-enable once we no longer have 200+ analyzer related deprecations.
    deprecated_member_use: ignore
    # Re-enable this once unused parameters are exempted (e.g. callback(_) {}).
    inference_failure_on_untyped_parameter: ignore
