# See https://github.com/dart-lang/mono_repo for details
dart:
  - dev

stages:
  - analyze:
    - dartanalyzer: --fatal-warnings lib test
  - build:
    - command: pub run build_runner build
  - unit_test:
    - command: pub run build_runner test -- --platform=chrome --timeout=4x -x skip_on_travis -j1
