language: dart
dart:
  - dev

dart_task:
  - dartanalyzer: --fatal-warnings lib test
  - test: -p vm
  - test: --precompiled=build --platform=chrome --tags=codegen --timeout=4x -x skip_on_travis -j1

before_script: tool/travis.sh
