name: angular_router.example
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/angular
description: Router example for AngularDart.
version: 1.0.0

environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

dependencies:
  angular: '^4.0.0'
  angular_forms: '^1.0.0'
  angular_router: '^2.0.0'

dev_dependencies:
  angular_test: ^1.0.2
  pageloader: ^2.2.5
  test: ^0.12.6

dependency_overrides:
  angular:
    path: ../../angular
  angular_ast:
    path: ../../angular_ast
  angular_compiler:
      path: ../../angular_compiler
  angular_forms:
      path: ../../angular_forms
  angular_router:
      path: ../../angular_router
  angular_test:
      path: ../../angular_test

transformers:
  - angular:
      entry_points:
          - web/main.dart
          - test/**_test.dart
  - test/pub_serve:
      $include: test/**_test.dart

web:
  compiler:
    debug: dartdevc
