dart:
- 2.12.0
- dev

stages:
- analyze:
  - group:
    - dartanalyzer: --fatal-infos .
    dart: dev
  - group:
    - dartanalyzer
    dart: 2.12.0
- build:
  - command: pub run build_runner build --fail-on-severe

