dart:
#- 2.12.0
- dev

stages:
- analyze:
  - group:
    - analyze: --fatal-infos
    dart: dev
#  - group:
#    - analyze
#    dart: 2.12.0
- build:
  - command: pub run build_runner build --fail-on-severe
