# See https://github.com/dart-lang/mono_repo for details
dart:
  - dev

stages:
  - analyze:
    - dartanalyzer: --fatal-warnings lib test
  - build:
    - command: pub run build_runner build --fail-on-severe
  - unit_test:
    - command: pub run build_runner test -- -p vm
    - command: pub run build_runner test -- --platform=chrome --exclude-tags=known_pub_serve_failure
