targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          include:
          - test/**.browser_test.dart
          exclude:
          - test/compiler/**
          - test/compiler_integration/**
          - test/source_gen/**
          - test/core/di/provider_test.dart*
          - test/regression/906_incorrect_injectable_warning_test.dart*
          - test/regression/519_missing_query_selector_test.dart*
          - test/regression/1500_factory_provider_null_test.dart*
          - test/regression/1538_deferred_template_test.dart*
          - test/regression/function_event_bindings_test.dart*
