dart:
  - dev

stages:
  - analyze:
    - dartanalyzer: --fatal-warnings lib test
  - build:
    - command: pub run build_runner build
  - unit_test:
    - test: -p vm
    - command: pub run build_runner test -- --platform=chrome -j1
