targets:
  $default:
    builders:
      angular:
        generate_for:
          exclude: ["test/url_test.dart"]
      build_web_compilers|entrypoint:
        options:
          compiler: dart2js
          dart2js_args:
          - --preview-dart-2
