targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
        - web/**.dart
        options:
          dart2js_args:
          - --dump-info
          - --fast-startup
          - --minify
          - --trust-type-annotations
          - --trust-primitives
          - --no-source-maps
