# See https://github.com/dart-lang/mono_repo for details
dart:
  - dev

stages:
  - analyze:
    - dartanalyzer: --fatal-warnings lib test tool
  - build:
      - command: pub run build_runner build
  - unit_test:
    - test: -p vm --precompiled build
