# See https://github.com/dart-lang/mono_repo for details
dart:
  - dev

stages:
  - analyze:
    - dartanalyzer: --fatal-warnings .
  - unit_test:
    - command:
      - dart generator/bin/generate.dart
      - pub run test
