# See https://github.com/dart-lang/mono_repo for details
dart:
  - dev

stages:
  - analyze:
    - dartanalyzer: --fatal-warnings .
  - unit_test:
    - command:
      - pub run build_runner build -o build
      - pub run test --precompiled build
