targets:
  $default:
    sources: ["lib/**", "test/**", "tool/**"]
    builders:
      "angular|angular":
        enabled: false
      "|goldens":
        generate_for: ["test/_files/**"]
        options:
          extensions:
            release: ".template_release.check"
            outline: ".template_outline.check"

builders:
  goldens:
    target: "goldens"
    import: "../../../tool/src/builder.dart"
    builder_factories:
      - releaseBuilder
      - outlineBuilder
    build_extensions:
      ".dart":
        - ".template_release.check"
        - ".template_outline.check"
