dart:
  - stable
  - dev

stages:
  - analyze:
    - dartanalyzer: --fatal-warnings .
  - build:
    - command: pub run build_runner build --fail-on-severe
  - unit_test:
    - command: ./tool/test.sh
